const express = require("express");
require("dotenv").config();
const multer = require("multer");
const jwt = require('jsonwebtoken');
require("dotenv").config();
const UPLOAD_FOLDER = "./public/image";
const fs = require("fs");
const path = require("path");
const { log } = require("console");
const { request } = require("http");